# Basic
title: BeanBest
subtitle: PHPer
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 嗨，我是杜斌 (@sxdubin)，一名来自中国的 PHP / DevOps 开发者。现居深圳，就职于 Onething。
creator: <a href="http://beanbest.net">@sxdubin</a>

url: "http://beanbest.net"

permalink: /:year/:month/:title/
#permalink: /:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit Blog

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: , url: 'http://beanbest.net'}
    - {title: 关于, description: , url: 'http://beanbest.net'}
    - {title: 订阅, description: , url: 'http://beanbest.net/feed.xml'}
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
     #disqus: vno-jekyll
     disqus: beanbest
    # duoshuo: 
    
# Social
social:
    weibo: sxdubin
    github: sxdubin
    twitter: sxdubin
#    gplus: 118295134398737949230 
    mail: sxdubin@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
